[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.json"
    [headers.values]
    Content-Type = "application/json"
